use_frameworks!

platform :ios, '12.0'

target 'BlueXSDK_Example' do
  pod 'BlueXSDK', :path => '../'
  pod 'AppLovinSDK'
  pod 'TradPlusAdSDK', '13.0.0'
  pod 'TradPlusAdSDK/TPCrossAdapter', '13.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.12'
  pod 'TPNiOS'

  target 'BlueXSDK_Tests' do
    inherit! :search_paths

  end
end
